CC = c++ -Wall -static #-pg  -O3

OBJS = bibrand.o graph.o dgraph.o sgraph.o instance.o solution.o binrwa.o

prog: $(OBJS)
	$(CC) $(OBJS) main.cpp -o rwa

bibrand.o: bibrand.h bibrand.cpp
	$(CC) -c bibrand.cpp

graph.o: graph.h graph.cpp heap.h heapbucket.h linkedset.h
	$(CC) -c graph.cpp

dgraph.o: graph.h dgraph.cpp heap.h heapbucket.h linkedset.h
	$(CC) -c dgraph.cpp

sgraph.o: graph.h sgraph.cpp heap.h heapbucket.h linkedset.h
	$(CC) -c sgraph.cpp

instance.o: instance.h instance.cpp graph.o dgraph.o sgraph.o
	$(CC) -c instance.cpp

solution.o: solution.h solution.cpp instance.o
	$(CC) -c solution.cpp

binrwa.o: binrwa.h binrwa.cpp instance.o solution.o quicksort.h
	$(CC) -c binrwa.cpp

clean:
	rm *.o rwa *~ -f
